CREATE TABLE IF NOT EXISTS units(
   id serial PRIMARY KEY,
   name VARCHAR (150) NOT NULL,
   updatedAt TIMESTAMP NULL,
   createdAt TIMESTAMP NULL
);

INSERT INTO `units` (name) VALUES
('UDD PMI KETAPANG'),
('UDD PMI KETAPANG 1'),
('UDD PMI KETAPANG 2'),
('UDD PMI KETAPANG 3');