CREATE TABLE IF NOT EXISTS jobs(
   id serial PRIMARY KEY,
   name VARCHAR (150) NOT NULL,
   updatedAt TIMESTAMP NULL,
   createdAt TIMESTAMP NULL
);

INSERT INTO `jobs` (name) VALUES
('BELUM/TIDAK BEKERJA'),
('PELAJAR/MAHASISWA'),
('PENSIUNAN'),
('TENTARA NASIONAL INDONESIA'),
('PETANI/PEKEBUN'),
('NELAYAN/PERIKANAN'),
('PENDETA'),
('WAKIL GUBERNUR'),
('BUPATI'),
('GURU'),
('PERAWAT'),
('WIRASWASTA'),
('LAINNYA');