// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gomail "gopkg.in/gomail.v2"
)

// MailService is an autogenerated mock type for the MailService type
type MailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: mailer
func (_m *MailService) SendEmail(mailer *gomail.Message) error {
	ret := _m.Called(mailer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gomail.Message) error); ok {
		r0 = rf(mailer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMailService creates a new instance of MailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMailService(t mockConstructorTestingTNewMailService) *MailService {
	mock := &MailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
