// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bxcodec/go-clean-arch/domain"
	mock "github.com/stretchr/testify/mock"
)

// RegionUsecase is an autogenerated mock type for the RegionUsecase type
type RegionUsecase struct {
	mock.Mock
}

// GetDistrict provides a mock function with given fields: ctx
func (_m *RegionUsecase) GetDistrict(ctx context.Context) ([]*domain.DistrictData, error) {
	ret := _m.Called(ctx)

	var r0 []*domain.DistrictData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.DistrictData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.DistrictData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DistrictData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRegionUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegionUsecase creates a new instance of RegionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegionUsecase(t mockConstructorTestingTNewRegionUsecase) *RegionUsecase {
	mock := &RegionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
